FROM ubuntu:20.04

ARG PROFILE=release
ARG BINARY=baronchain-parachain
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends libssl1.1 ca-certificates curl tini && \
    apt-get autoremove -y && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY target/${PROFILE}/baronchain-parachain /usr/local/bin

RUN chmod +x /usr/local/bin/baronchain-parachain && \
    ldd /usr/local/bin/baronchain-parachain && \
    /usr/local/bin/baronchain-parachain --version

EXPOSE 30333 9933 9944
VOLUME ["/data"]

ENTRYPOINT ["tini", "--", "/usr/local/bin/baronchain-parachain"]
