[package]
authors = ["Interlay Ltd"]
edition = "2021"
name = 'parachain-tests'
version = "1.2.0"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
env_logger = { version = "0.9.1" }
log = { version = "0.4.14" }
serde = { version = "1.0.130", features = ["derive"], default-features = false }
codec = { package = "parity-scale-codec", version = "3.1.5", features = ["derive", "max-encoded-len"] }
hex-literal = { version = "0.3.1" }
scale-info = { version = "2.2.0", features = ["derive"] }
libsecp256k1 = { version = "0.6" }
pretty_assertions = "0.7.2"
itertools = "0.10.0"
flate2 = "1.0"
rand = "0.8.5"

# Substrate dependencies
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
frame-executive = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", optional = true }
frame-system-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", optional = true }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
pallet-utility = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
pallet-multisig = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
pallet-sudo = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
pallet-preimage = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
pallet-contracts = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
pallet-contracts-primitives = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

## Governance
pallet-collective = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
pallet-membership = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
pallet-society = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

# Aura dependencies
pallet-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
pallet-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
pallet-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }

# Cumulus dependencies
cumulus-pallet-aura-ext = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v1.0.0" }
cumulus-pallet-parachain-system = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v1.0.0" }
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v1.0.0" }
cumulus-primitives-timestamp = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v1.0.0" }
cumulus-primitives-utility = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v1.0.0" }
cumulus-pallet-dmp-queue = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v1.0.0" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v1.0.0" }
cumulus-pallet-xcm = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v1.0.0" }
cumulus-test-relay-sproof-builder = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v1.0.0"  }
cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v1.0.0"  }
parachain-info = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v1.0.0" }
xcm-emulator = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v1.0.0" }

# Polkadot dependencies
polkadot-parachain = { git = "https://github.com/paritytech//polkadot", branch = "release-v1.0.0" }
polkadot-primitives = { git = "https://github.com/paritytech//polkadot", branch = "release-v1.0.0" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech//polkadot", branch = "release-v1.0.0" }
kusama-runtime = { git = "https://github.com/paritytech//polkadot", branch = "release-v1.0.0"  }
polkadot-runtime = { git = "https://github.com/paritytech//polkadot", branch = "release-v1.0.0"  }
xcm = { git = "https://github.com/paritytech//polkadot", branch = "release-v1.0.0" }
xcm-builder = { git = "https://github.com/paritytech//polkadot", branch = "release-v1.0.0" }
xcm-executor = { git = "https://github.com/paritytech//polkadot", branch = "release-v1.0.0" }
xcm-simulator = { git = "https://github.com/paritytech//polkadot", branch = "release-v1.0.0" }
pallet-xcm = { git = "https://github.com/paritytech//polkadot", branch = "release-v1.0.0" }
polkadot-test-runtime = { git = "https://github.com/paritytech/polkadot", branch = "release-v1.0.0" }

# Parachain dependencies
runtime-common = { path = "../common" }
btc-relay = { path = "../../../crates/btc-relay" }
currency = { path = "../../../crates/currency", features = ["testing-utils"] }
security = { path = "../../../crates/security" }
vault-registry = { path = "../../../crates/vault-registry", features = ["integration-tests"] }
oracle = { path = "../../../crates/oracle", features = ["testing-utils"]  }
fee = { path = "../../../crates/fee" }
issue = { path = "../../../crates/issue" }
redeem = { path = "../../../crates/redeem" }
replace = { path = "../../../crates/replace" }
nomination = { path = "../../../crates/nomination" }
reward = { path = "../../../crates/reward" }
staking = { path = "../../../crates/staking", features = ["integration-tests"] }
escrow = { path = "../../../crates/escrow" }
democracy = { path = "../../../crates/democracy" }
annuity = { path = "../../../crates/annuity" }
supply = { path = "../../../crates/supply" }
collator-selection = { path = "../../../crates/collator-selection" }
clients-info = { path = "../../../crates/clients-info" }
loans = { path = "../../../crates/loans", features = ["integration-tests"] }
traits = { path = "../../../crates/traits" }
farming = { path = "../../../crates/farming" }
tx-pause = { path = "../../../crates/tx-pause" }
dex-general = { path = "../../../crates/dex-general" }
dex-stable = { path = "../../../crates/dex-stable" }
dex-swap-router = { path = "../../../crates/dex-swap-router" }
multi-transaction-payment = { path = "../../../crates/multi-transaction-payment" }

kintsugi-runtime-parachain = { path = "../kintsugi", features = ["vesting-any"] }
interlay-runtime-parachain = { path = "../interlay", features = ["vesting-any"] }

primitives = { package = "interbtc-primitives", path = "../../../primitives" }

btc-relay-rpc-runtime-api = { path = "../../../crates/btc-relay/rpc/runtime-api" }
oracle-rpc-runtime-api = { path = "../../../crates/oracle/rpc/runtime-api" }
vault-registry-rpc-runtime-api = { path = "../../../crates/vault-registry/rpc/runtime-api" }
issue-rpc-runtime-api = { path = "../../../crates/issue/rpc/runtime-api" }
redeem-rpc-runtime-api = { path = "../../../crates/redeem/rpc/runtime-api" }
replace-rpc-runtime-api = { path = "../../../crates/replace/rpc/runtime-api" }
reward-rpc-runtime-api = { path = "../../../crates/reward/rpc/runtime-api" }

# Orml dependencies
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404" }
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404" }
orml-vesting = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404" }

orml-xtokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404" }
orml-xcm = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404" }
orml-xcm-support = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404" }
orml-unknown-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404" }

# Frontier dependencies
ethereum = { version = "0.14.0", default-features = false, features = ["with-codec"] }
fp-ethereum = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42" }
fp-evm = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42" }
fp-rpc = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42" }
pallet-ethereum = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42" }
pallet-evm = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42" }
pallet-evm-chain-id = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42" }

[dev-dependencies]
hex = '0.4.2'
mocktopus = "0.8.0"
serde_json = "1.0"

bitcoin = { path = "../../../crates/bitcoin", features = ["parser"] }

[features]
default = ["std"]
std = []
skip-slow-tests = []
runtime-benchmarks = [
  "frame-benchmarking",
  "frame-system-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "pallet-society/runtime-benchmarks",
  "pallet-collective/runtime-benchmarks",

  "xcm-builder/runtime-benchmarks",
  "pallet-xcm/runtime-benchmarks",

  "btc-relay/runtime-benchmarks",
  "oracle/runtime-benchmarks",
  "issue/runtime-benchmarks",
  "redeem/runtime-benchmarks",
  "replace/runtime-benchmarks",
  "vault-registry/runtime-benchmarks",
  "fee/runtime-benchmarks",
  "security/runtime-benchmarks",

  "kusama-runtime/runtime-benchmarks",
  "polkadot-runtime/runtime-benchmarks",
  "polkadot-test-runtime/runtime-benchmarks",
]
with-interlay-runtime = []
