[package]
authors = ["Interlay Ltd"]
edition = "2021"
name    = "loans-rpc-runtime-api"
version = "1.9.3"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false, features = ["derive"] }
primitives = { package = "interbtc-primitives", path = "../../../../primitives", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.31", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.31", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "primitives/std",
    "sp-api/std",
    "sp-runtime/std"
]

[lib]
doctest = false
