[package]
authors = ["Parallel Team", "Interlay Ltd"]
edition = "2021"
name = "traits"
version = "1.9.3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.136", default-features = false, features = [
  "derive",
] }
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false }
scale-info = { version = "2.2.0", default-features = false, features = [
  "derive",
] }
num-traits = { default-features = false, version = "0.2" }
log = { version = "0.4", default-features = false }
num-bigint = { default-features = false, version = "0.4" }
impl-trait-for-tuples = "0.2.2"

# Substrate dependencies
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.31", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.31", default-features = false }

# Parachain dependencies
primitives = { package = "interbtc-primitives", path = "../../primitives", default-features = false, features = ["substrate-compat"] }

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.31" }

[features]
default = ["std"]
std = [
  "serde/std",
  "codec/std",
  "frame-support/std",
  "frame-system/std",
  "log/std",
  "num-bigint/std",
  "num-traits/std",
  "primitives/std",
  "scale-info/std",
  "sp-core/std",
  "sp-io/std",
  "sp-runtime/std",
  "sp-std/std",
]
runtime-benchmarks = []
try-runtime = ["frame-support/try-runtime"]

[lib]
doctest = false
