[package]
authors = ["Interlay Ltd"]
edition = "2021"
name = 'interlay-runtime-parachain'
version = "1.2.0"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false, features = ["derive", "max-encoded-len"] }
hex-literal = { version = "0.3.1" }
scale-info = { version = "2.2.0", default-features = false, features = ["derive"] }

# Substrate dependencies
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-weights = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
frame-executive = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
frame-system-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false, optional = true }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false, optional = true }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-sudo = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-utility = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-multisig = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-preimage = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-identity = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-proxy = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }

frame-try-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false, optional = true }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }

## Governance
pallet-collective = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-membership = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-society = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }

# Aura dependencies
pallet-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }

# Cumulus dependencies
cumulus-pallet-aura-ext = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.31", default-features = false }
cumulus-pallet-dmp-queue = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.31", default-features = false }
cumulus-pallet-parachain-system = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.31", default-features = false }
cumulus-pallet-xcm = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.31", default-features = false }
cumulus-pallet-xcmp-queue = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.31", default-features = false }
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.31", default-features = false }
cumulus-primitives-timestamp = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.31", default-features = false }
cumulus-primitives-utility = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.31", default-features = false }
parachain-info = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.31", default-features = false }

# Polkadot dependencies
pallet-xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.31", default-features = false }
pallet-xcm-benchmarks = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.31", default-features = false, optional = true }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.31", default-features = false }
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.31", default-features = false }
xcm-builder = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.31", default-features = false }
xcm-executor = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.31", default-features = false }

# Parachain dependencies
annuity = { path = "../../../crates/annuity", default-features = false }
btc-relay = { path = "../../../crates/btc-relay", default-features = false }
clients-info = { path = "../../../crates/clients-info", default-features = false }
collator-selection = { path = "../../../crates/collator-selection", default-features = false }
currency = { path = "../../../crates/currency", default-features = false }
democracy = { path = "../../../crates/democracy", default-features = false }
dex-general = { path = "../../../crates/dex-general", default-features = false }
dex-stable = { path = "../../../crates/dex-stable", default-features = false }
dex-swap-router = { path = "../../../crates/dex-swap-router", default-features = false }
escrow = { path = "../../../crates/escrow", default-features = false }
farming = { path = "../../../crates/farming", default-features = false }
fee = { path = "../../../crates/fee", default-features = false }
issue = { path = "../../../crates/issue", default-features = false }
loans = { path = "../../../crates/loans", default-features = false }
multi-transaction-payment = { path = "../../../crates/multi-transaction-payment", default-features = false }
nomination = { path = "../../../crates/nomination", default-features = false }
oracle = { path = "../../../crates/oracle", default-features = false }
redeem = { path = "../../../crates/redeem", default-features = false }
replace = { path = "../../../crates/replace", default-features = false }
reward = { path = "../../../crates/reward", default-features = false }
security = { path = "../../../crates/security", default-features = false }
staking = { path = "../../../crates/staking", default-features = false }
supply = { path = "../../../crates/supply", default-features = false }
traits = { path = "../../../crates/traits", default-features = false }
tx-pause = { path = "../../../crates/tx-pause", default-features = false }
vault-registry = { path = "../../../crates/vault-registry", default-features = false }

primitives = { package = "interbtc-primitives", path = "../../../primitives", default-features = false }
runtime-common = {path = "../common", default-features = false }

btc-relay-rpc-runtime-api = { path = "../../../crates/btc-relay/rpc/runtime-api", default-features = false }
dex-general-rpc-runtime-api = { path = "../../../crates/dex-general/rpc/runtime-api", default-features = false }
dex-stable-rpc-runtime-api = { path = "../../../crates/dex-stable/rpc/runtime-api", default-features = false }
escrow-rpc-runtime-api = { path = "../../../crates/escrow/rpc/runtime-api", default-features = false }
issue-rpc-runtime-api = { path = "../../../crates/issue/rpc/runtime-api", default-features = false }
loans-rpc-runtime-api = { path = "../../../crates/loans/rpc/runtime-api", default-features = false }
oracle-rpc-runtime-api = { path = "../../../crates/oracle/rpc/runtime-api", default-features = false }
redeem-rpc-runtime-api = { path = "../../../crates/redeem/rpc/runtime-api", default-features = false }
replace-rpc-runtime-api = { path = "../../../crates/replace/rpc/runtime-api", default-features = false }
reward-rpc-runtime-api = { path = "../../../crates/reward/rpc/runtime-api", default-features = false }
vault-registry-rpc-runtime-api = { path = "../../../crates/vault-registry/rpc/runtime-api", default-features = false }

# Orml dependencies
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404", default-features = false }
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404", default-features = false }
orml-vesting = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404", default-features = false }
orml-asset-registry = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404", default-features = false }

orml-xtokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404", default-features = false }
orml-xcm-support = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404", default-features = false }
orml-unknown-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404", default-features = false }

# Frontier dependencies
fp-rpc = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42", default-features = false }
fp-self-contained = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42", default-features = false, features = ["serde"] }
pallet-base-fee = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42", default-features = false }
pallet-ethereum = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42", default-features = false }
pallet-evm = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42", default-features = false }
pallet-evm-chain-id = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42", default-features = false }
pallet-evm-precompile-dispatch = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42", default-features = false }

[dev-dependencies]
hex = '0.4.2'
mocktopus = "0.8.0"
serde_json = "1.0"

bitcoin = { path = "../../../crates/bitcoin", default-features = false }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }

[features]
default = ["std"]
disable-runtime-api = []
vesting-any = []
std = [
  "serde/std",
  "codec/std",

  "sp-std/std",
  "sp-api/std",
  "sp-io/std",
  "sp-version/std",
  "sp-runtime/std",
  "sp-core/std",
  "sp-session/std",
  "sp-offchain/std",
  "sp-block-builder/std",
  "sp-transaction-pool/std",
  "sp-inherents/std",
  "sp-arithmetic/std",

  "frame-try-runtime?/std",
  "frame-support/std",
  "frame-executive/std",
  "frame-system/std",
  "frame-system-benchmarking?/std",
  "frame-benchmarking/std",
  "pallet-balances/std",
  "pallet-timestamp/std",
  "pallet-sudo/std",
  "pallet-utility/std",
  "pallet-transaction-payment/std",
  "pallet-scheduler/std",
  "pallet-multisig/std",
  "pallet-preimage/std",
  "pallet-identity/std",
  "pallet-proxy/std",

  "frame-system-rpc-runtime-api/std",
  "pallet-transaction-payment-rpc-runtime-api/std",

  "pallet-collective/std",
  "pallet-membership/std",
  "pallet-society/std",

  "pallet-authorship/std",
  "pallet-session/std",
  "pallet-aura/std",
  "sp-consensus-aura/std",

  "cumulus-pallet-aura-ext/std",
  "cumulus-pallet-dmp-queue/std",
  "cumulus-pallet-parachain-system/std",
  "cumulus-pallet-xcm/std",
  "cumulus-pallet-xcmp-queue/std",
  "cumulus-primitives-core/std",
  "cumulus-primitives-timestamp/std",
  "cumulus-primitives-utility/std",
  "parachain-info/std",

  "pallet-xcm/std",
  "pallet-xcm-benchmarks?/std",
  "polkadot-parachain/std",
  "xcm/std",
  "xcm-builder/std",
  "xcm-executor/std",

  "annuity/std",
  "btc-relay/std",
  "clients-info/std",
  "collator-selection/std",
  "currency/std",
  "democracy/std",
  "dex-general/std",
  "dex-stable/std",
  "dex-swap-router/std",
  "escrow/std",
  "farming/std",
  "fee/std",
  "issue/std",
  "loans/std",
  "multi-transaction-payment/std",
  "nomination/std",
  "oracle/std",
  "redeem/std",
  "replace/std",
  "reward/std",
  "security/std",
  "staking/std",
  "supply/std",
  "traits/std",
  "tx-pause/std",
  "vault-registry/std",

  "primitives/std",
  "runtime-common/std",

  "btc-relay-rpc-runtime-api/std",
  "dex-general-rpc-runtime-api/std",
  "dex-stable-rpc-runtime-api/std",
  "escrow-rpc-runtime-api/std",
  "issue-rpc-runtime-api/std",
  "loans-rpc-runtime-api/std",
  "oracle-rpc-runtime-api/std",
  "redeem-rpc-runtime-api/std",
  "replace-rpc-runtime-api/std",
  "reward-rpc-runtime-api/std",
  "vault-registry-rpc-runtime-api/std",

  "orml-tokens/std",
  "orml-traits/std",
  "orml-vesting/std",
  "orml-asset-registry/std",

  "orml-xtokens/std",
  "orml-xcm-support/std",
  "orml-unknown-tokens/std",

  "fp-rpc/std",
  "fp-self-contained/std",
  "pallet-base-fee/std",
  "pallet-ethereum/std",
  "pallet-evm/std",
  "pallet-evm-chain-id/std",
  "pallet-evm-precompile-dispatch/std",
]
runtime-benchmarks = [
  "frame-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "frame-system-benchmarking/runtime-benchmarks",
  "pallet-balances/runtime-benchmarks",
  "pallet-collective/runtime-benchmarks",
  "pallet-identity/runtime-benchmarks",
  "pallet-membership/runtime-benchmarks",
  "pallet-multisig/runtime-benchmarks",
  "pallet-preimage/runtime-benchmarks",
  "pallet-proxy/runtime-benchmarks",
  "pallet-scheduler/runtime-benchmarks",
  "pallet-timestamp/runtime-benchmarks",
  "pallet-utility/runtime-benchmarks",
  "pallet-society/runtime-benchmarks",

  "cumulus-pallet-xcmp-queue/runtime-benchmarks",
  "cumulus-pallet-parachain-system/runtime-benchmarks",

  "pallet-xcm/runtime-benchmarks",
  "pallet-xcm-benchmarks/runtime-benchmarks",
  "xcm-builder/runtime-benchmarks",

  "annuity/runtime-benchmarks",
  "btc-relay/runtime-benchmarks",
  "clients-info/runtime-benchmarks",
  "collator-selection/runtime-benchmarks",
  "democracy/runtime-benchmarks",
  "dex-general/runtime-benchmarks",
  "dex-stable/runtime-benchmarks",
  "dex-swap-router/runtime-benchmarks",
  "escrow/runtime-benchmarks",
  "farming/runtime-benchmarks",
  "fee/runtime-benchmarks",
  "issue/runtime-benchmarks",
  "loans/runtime-benchmarks",
  "nomination/runtime-benchmarks",
  "oracle/runtime-benchmarks",
  "redeem/runtime-benchmarks",
  "replace/runtime-benchmarks",
  "security/runtime-benchmarks",
  "supply/runtime-benchmarks",
  "traits/runtime-benchmarks",
  "tx-pause/runtime-benchmarks",
  "vault-registry/runtime-benchmarks",

  "primitives/runtime-benchmarks",
  "runtime-common/runtime-benchmarks",

  "pallet-ethereum/runtime-benchmarks",
  "pallet-evm/runtime-benchmarks",
]
try-runtime = [
  "frame-try-runtime",
  "frame-executive/try-runtime",
  "frame-system/try-runtime",
  "frame-support/try-runtime",

  "pallet-aura/try-runtime",
  "pallet-authorship/try-runtime",
  "pallet-collective/try-runtime",
  "pallet-identity/try-runtime",
  "pallet-membership/try-runtime",
  "pallet-multisig/try-runtime",
  "pallet-preimage/try-runtime",
  "pallet-proxy/try-runtime",
  "pallet-session/try-runtime",
  "pallet-scheduler/try-runtime",
  "pallet-sudo/try-runtime",
  "pallet-timestamp/try-runtime",
  "pallet-transaction-payment/try-runtime",
  "pallet-utility/try-runtime",

  "cumulus-pallet-aura-ext/try-runtime",
  "cumulus-pallet-dmp-queue/try-runtime",
  "cumulus-pallet-parachain-system/try-runtime",
  "cumulus-pallet-xcm/try-runtime",
  "cumulus-pallet-xcmp-queue/try-runtime",
  "parachain-info/try-runtime",

  "pallet-xcm/try-runtime",

  "annuity/try-runtime",
  "btc-relay/try-runtime",
  "clients-info/try-runtime",
  "currency/try-runtime",
  "collator-selection/try-runtime",
  "democracy/try-runtime",
  "dex-general/try-runtime",
  "dex-stable/try-runtime",
  "dex-swap-router/try-runtime",
  "escrow/try-runtime",
  "farming/try-runtime",
  "fee/try-runtime",
  "issue/try-runtime",
  "loans/try-runtime",
  "multi-transaction-payment/try-runtime",
  "nomination/try-runtime",
  "oracle/try-runtime",
  "redeem/try-runtime",
  "replace/try-runtime",
  "reward/try-runtime",
  "security/try-runtime",
  "staking/try-runtime",
  "supply/try-runtime",
  "tx-pause/try-runtime",
  "vault-registry/try-runtime",

  "runtime-common/try-runtime",

  "orml-tokens/try-runtime",
  "orml-vesting/try-runtime",
  "orml-asset-registry/try-runtime",
  "orml-xtokens/try-runtime",
  "orml-unknown-tokens/try-runtime",

  "fp-self-contained/try-runtime",
  "pallet-base-fee/try-runtime",
  "pallet-ethereum/try-runtime",
  "pallet-evm/try-runtime",
  "pallet-evm-chain-id/try-runtime",
]