[package]
authors = ["Interlay Ltd"]
edition = "2021"
name    = "loans-rpc"
version = "1.9.3"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.5" }
jsonrpsee = { version = "0.16.2", features = ["server", "macros"] }
primitives = { package = "interbtc-primitives", path = "../../../primitives" }
serde = { version = "1.0.136", features = ["derive"], default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.31" }
sp-blockchain = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.31" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.31" }
sp-rpc = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.31" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.31" }

loans-rpc-runtime-api = { path = "runtime-api" }

[lib]
doctest = false
