name: Publish Rust doc

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow
      - name: Install System Dependencies
        run: |
            sudo apt-get update && sudo apt-get install -y \
            cmake pkg-config libssl-dev git clang curl libc6-dev protobuf-compiler
      - name: Set variables
        run: |
            echo "TOOLCHAIN=$(rustup show active-toolchain | cut -d " " -f1)" >> $GITHUB_ENV
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.TOOLCHAIN }}
      - name: build docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps
      - name: copy index.html
        run: cp .github/docs-index.html target/doc/index.html
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: target/doc/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
